import os
import sys
import argparse

try:
    from bfbarchitect.datatypes import SV, chrom_sort_key, build_centromere_dict
    from bfbarchitect.BFBArchitect import reconstruct_BFB
    from bfbarchitect.BFBVisualizer import visualize_BFB
except ImportError:
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)
    from bfbarchitect.datatypes import SV, chrom_sort_key, build_centromere_dict
    from bfbarchitect.BFBArchitect import reconstruct_BFB
    from bfbarchitect.BFBVisualizer import visualize_BFB

def parse_SV(sv_str):
    # e.g., chr3:24524687-->chr3:24523614-
    bkp1, bkp2 = sv_str.split("->")
    chr1, pos1_dir1 = bkp1.split(":")
    pos1, dir1 = pos1_dir1[:-1], pos1_dir1[-1]
    chr2, pos2_dir2 = bkp2.split(":")
    pos2, dir2 = pos2_dir2[:-1], pos2_dir2[-1]
    return SV(chr1, int(pos1), dir1, chr2, int(pos2), dir2)

def find_foldbacks(directory):
    """
    Find all files ending with 'graph.txt' in the directory.
    For each file, extract foldback SV.
    Return sorted foldback SVs by chromosome and position.
    """
    foldbacks = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith('graph.txt'):
                filepath = os.path.join(root, file)
                with open(filepath, 'r') as f:
                    for line in f:
                        if line.startswith('discordant'):
                            sv_str = line.split()[1] # The SV string, e.g., "chr3:24524687-->chr3:24523614-"
                            sv = parse_SV(sv_str)
                            if sv.is_foldback():
                                foldbacks.append(sv)
    return foldbacks

def cluster_foldbacks(foldbacks, distance_threshold=5000000):
    """
    Cluster foldback SVs that are within distance_threshold of each other.
    Return a list of clusters, where each cluster is a list of SVs.
    """
    clusters = []
    unclustered_foldbacks = foldbacks.copy()
    current_cluster = []
    while unclustered_foldbacks:
        if current_cluster:
            current_sv = current_cluster[-1]
        else:
            current_sv = unclustered_foldbacks.pop(0)
            current_cluster.append(current_sv)
        # find the closest SV to current_sv
        closest_sv = None
        closest_distance = float('inf')
        for sv in unclustered_foldbacks:
            if sv.chrom1 == current_sv.chrom1:
                distance = abs(sv.bp1 - current_sv.bp1)
                if distance < closest_distance:
                    closest_distance = distance
                    closest_sv = sv
        if closest_sv and closest_distance <= distance_threshold:
            unclustered_foldbacks.remove(closest_sv)
            current_cluster.append(closest_sv)
        else:
            current_cluster.sort(key=lambda sv: (chrom_sort_key(sv.chrom1), sv.bp1))
            clusters.append(current_cluster)
            current_cluster = []
    if current_cluster:
        current_cluster.sort(key=lambda sv: (chrom_sort_key(sv.chrom1), sv.bp1))
        clusters.append(current_cluster)
    # sort clusters by the position of the first SV in each cluster
    clusters.sort(key=lambda cluster: (chrom_sort_key(cluster[0].chrom1), cluster[0].bp1))
    return clusters

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run BFBArchitect based on CoRAL outputs at whole-genome level.")
    parser.add_argument("--directory", help="Directory containing CoRAL graph files")
    parser.add_argument("--bam", help = "Path to a sorted bam file", required = True)
    parser.add_argument("--cns", help = "Path to a sorted cns file generated by CNVKit", required = True)
    parser.add_argument("--output_prefix", help = "Prefix of output files.", required=True)
    parser.add_argument("--segmentation", help="Consider CNV in segmentation", action='store_true')
    parser.set_defaults(deletion=True)
    parser.add_argument("--deletion", dest="deletion", action="store_true",
                        help="Enable deletion handling (default; retained for compatibility).")
    parser.add_argument("--no-deletion", dest="deletion", action="store_false",
                        help="Disable deletion handling.")
    parser.add_argument("--coverage", help="Sequencing coverage (if provided, estimation from cns will be skipped)", type=float, default=None)
    parser.add_argument("--multiple", help="Reconstruct multiple BFB candidates", action='store_true')
    parser.add_argument("--no_expansion", help="Keep the specified region without expansion", action='store_true')
    parser.add_argument("--min_sv_cn", type=float, default=0.75, help="Minimum copy number for SV calling (default: 0.75)")
    parser.add_argument("--min_mapq", type=int, default=20, help="Minimum mapping quality for SV calling (default: 20)")
    parser.add_argument("--solver", help="ILP solver to use: 'gurobi' or 'cbc' (default: gurobi)", default='gurobi')
    parser.add_argument("--gene", help="Gene annotation", default=None)
    parser.add_argument("--centromere", help="Path to a centromere BED file (hg38 defaults used if not provided). "
                        "An example GRCh38 file is provided at resources/GRCh38_centromere.bed.", default=None)
    args = parser.parse_args()
    centromere_dict = build_centromere_dict(args.centromere)
    foldbacks = find_foldbacks(args.directory)
    foldback_clusters = cluster_foldbacks(foldbacks)
    for i, cluster in enumerate(foldback_clusters):
        print(f"Cluster {i+1}:")
        for sv in cluster:
            print(f"  {sv}")
    for i, cluster in enumerate(foldback_clusters):
        chrom, start, end = cluster[0].chrom1, cluster[0].bp1, cluster[-1].bp1 if len(cluster) > 1 else cluster[0].bp2
        region_str = f"{chrom}:{start}-{end}"
        print(f"Cluster {i+1}: amplified region {region_str}")
        reconstruct_BFB(bam_fn=args.bam,
            cns_fn=args.cns,
            region=region_str,
            output_prefix=f'{args.output_prefix}_amplicon{i+1}',
            segmentation=args.segmentation,
            deletion=args.deletion,
            coverage=args.coverage,
            multiple=args.multiple,
            no_expansion=args.no_expansion,
            min_sv_cn=args.min_sv_cn,
            min_mapq=args.min_mapq,
            solver=args.solver,
            centromere_dict=centromere_dict,
        )
        try:
            visualize_BFB(cycle_file=f'{args.output_prefix}_amplicon{i+1}_cycles.txt',
                graph_file=f'{args.output_prefix}_amplicon{i+1}_graph.txt',
                cnr_file=args.cns.replace('.cns', '.cnr'),
                output_prefix=f'{args.output_prefix}_amplicon{i+1}',
                gene_annotation=args.gene,
                multiple=args.multiple,
                centromere_dict=centromere_dict,
            )
        except:
            print(f"No visualization generated for amplicon {i+1}.")
